image: registry.gitlab.com/wldhx/gitlab-ci-react-native-android:master

stages:
  - install
  - test_coverage_lint
  - build
  - publish

before_script:
  - apt-get install -y tzdata
  - dpkg-reconfigure tzdata
  - unlink /etc/localtime
  - ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
  - dpkg-reconfigure tzdata
  - echo "//tool.wiidii.com:8081/repository/npm-group/:_authToken=$NPM_TOKEN" > $HOME/.npmrc
  - echo "email=contact@wiidii.com" >> $HOME/.npmrc
  - echo "always-auth=true" >> $HOME/.npmrc
  - echo "_auth=$NPM_AUTH" >> $HOME/.npmrc

npm install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
    expire_in: 10 min
  retry: 2

npm run test:
  stage: test_coverage_lint
  script:
    - npm run test
  retry: 2

npm run lint:
  stage: test_coverage_lint
  script:
    - npm run lint
  retry: 2

npm run build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 10 min
  retry: 2

npm run publish:
  stage: publish
  script:
    - npm run publish
  only:
    - master
  retry: 2
