stages:
  - package
  - deploy

docker build/push:
  stage: package
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  only:
    - master

sullust staging:
  stage: deploy
  image:
    name: ${CI_REGISTRY}/wiidii/tool/sullust:latest
    entrypoint: [""]
  script:
    - dotnet /app/Sullust.dll -ti ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -ml ${MARATHON_USER_STAG} -mp ${MARATHON_PASS_STAG} -mu ${MARATHON_URL_STAG} -gt ${SULLUST_GITLAB_TOKEN} -gu ${GITLAB_URL} -tbu ${TRAEFIK_BACK_URL_STAG} -tfs ${TRAEFIK_FRONT_SUFFIX_STAG} -ma ${MONGO_ADMIN_URL_STAG} -env ${ENVIRONMENT_STAG} -mlu ${MARATHON_LB_URL_STAG}
  environment: staging
  artifacts:
    name: "dump-${CI_JOB_NAME}-${CI_PROJECT_NAME}-${CI_COMMIT_SHA}"
    paths:
      - dump/
    expire_in: 1 hour
  only:
    - master

sullust production:
  stage: deploy
  image:
    name: ${CI_REGISTRY}/wiidii/tool/sullust:latest
    entrypoint: [""]
  script:
    - dotnet /app/Sullust.dll -ti ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} -ml ${MARATHON_USER_PROD} -mp ${MARATHON_PASS_PROD} -mu ${MARATHON_URL_PROD} -gt ${SULLUST_GITLAB_TOKEN} -gu ${GITLAB_URL} -tbu ${TRAEFIK_BACK_URL_PROD} -tfs ${TRAEFIK_FRONT_SUFFIX_PROD} -ma ${MONGO_ADMIN_URL_PROD} -env ${ENVIRONMENT_PROD} -mlu ${MARATHON_LB_URL_PROD}
  environment: production
  when: manual
  artifacts:
    name: "dump-${CI_JOB_NAME}-${CI_PROJECT_NAME}-${CI_COMMIT_SHA}"
    paths:
      - dump/
    expire_in: 1 hour
  only:
    - master
