# SPDX-License-Identifier: MIT-0
---

proxmox_provision_clone:
  - name: cephaloid
    state: present

    clone: arbitrary_name
    vmid: 90100
    newid: 202
    fullclone: false

    storage: Store1
    format: qcow2

    ciuser: valois
    cipassword: valois
    sshkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMH31hJ09NNiOSzdw5Ydygq5ex+J+C6FOH6i6pLr7nKC valois@teknomage"

    timeout: 1200

  - name: poulpy
    state: present

    clone: arbitrary_name
    vmid: 90100
    newid: 203
    fullclone: false

    storage: Store1
    format: qcow2

    ciuser: valois
    cipassword: valois
    sshkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMH31hJ09NNiOSzdw5Ydygq5ex+J+C6FOH6i6pLr7nKC valois@teknomage"

    timeout: 1200

  - name: ikamusume
    state: present

    clone: arbitrary_name
    vmid: 90000
    newid: 204
    fullclone: false

    storage: Store1
    format: qcow2

    ciuser: valois
    cipassword: valois
    sshkeys:
      - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMH31hJ09NNiOSzdw5Ydygq5ex+J+C6FOH6i6pLr7nKC valois@teknomage"

    timeout: 1200

proxmox_provision_vm: []
proxmox_provision_ct: []
