stages:
- build

docker build/push:
    stage: build
    image: docker:latest
    only:
        - master
    services:
        - docker:dind
    variables:
        DOCKER_DRIVER: overlay2
    script:
        - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
        - docker build --build-arg PYPI_IP_STAG=${PYPI_IP_STAG} --build-arg PYPI_PORT_STAG=${PYPI_PORT_STAG} --build-arg ARG_MLFLOW_TRACKING_URI=${ARG_MLFLOW_TRACKING_URI} --build-arg ARG_AWS_ACCESS_KEY_ID=${ARG_AWS_ACCESS_KEY_ID} --build-arg ARG_AWS_SECRET_ACCESS_KEY=${ARG_AWS_SECRET_ACCESS_KEY} -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
        - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
